// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzTrghaS_xwwakH_KaKeLd7TGh8L1M2I',
    appId: '1:361054156268:web:9710e57c4001000cc0fcc9',
    messagingSenderId: '361054156268',
    projectId: 'documed-696969',
    authDomain: 'documed-696969.firebaseapp.com',
    storageBucket: 'documed-696969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiNZE42--JtYQ5CPmP8CW_Xf0EJY3K8w',
    appId: '1:361054156268:android:331aa92263ab86a8c0fcc9',
    messagingSenderId: '361054156268',
    projectId: 'documed-696969',
    storageBucket: 'documed-696969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_R0NabJEHOuK4iKw8FCB4Sk_1jiNk7tw',
    appId: '1:361054156268:ios:ed7be6f1be67c9b3c0fcc9',
    messagingSenderId: '361054156268',
    projectId: 'documed-696969',
    storageBucket: 'documed-696969.appspot.com',
    iosBundleId: 'com.example.documed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_R0NabJEHOuK4iKw8FCB4Sk_1jiNk7tw',
    appId: '1:361054156268:ios:ed7be6f1be67c9b3c0fcc9',
    messagingSenderId: '361054156268',
    projectId: 'documed-696969',
    storageBucket: 'documed-696969.appspot.com',
    iosBundleId: 'com.example.documed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfzTrghaS_xwwakH_KaKeLd7TGh8L1M2I',
    appId: '1:361054156268:web:7b81d49e82dee8e5c0fcc9',
    messagingSenderId: '361054156268',
    projectId: 'documed-696969',
    authDomain: 'documed-696969.firebaseapp.com',
    storageBucket: 'documed-696969.appspot.com',
  );
}
